In [1]:
import numpy as np
print(np.__version__)

2.5.2


## Arrays

- It converts every elements to a single datatype

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr = np.array([1, 3.14, "Hello"])
arr

array(['1', '3.14', 'Hello'], dtype='<U32')

In [4]:
arr = np.array([1, 2, 3, 4, 5.1])
arr

array([1. , 2. , 3. , 4. , 5.1])

- Multiple dimensions
    - 2D arrays
    - 3D arrays
    - etc.

In [ ]:
two_d = np.array([
    [1, 2, 3],
    [4, 5, 6]])

two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_d.shape     # Two rows, three columns

(2, 3)

### Creating arrays:

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# For a specific number:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.arange(0, 10, 2)   # Start, stop, step

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0, 10, 5)       # Five evenly spaced numbers between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.logspace(0, 10, 5)       # Five logarithmically spaced numbers between 0 and 10

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

#### Random arrays

In [24]:
seed = np.random.seed((42))
rand = np.random.rand( 3)
randn = np.random.randn(3)
randint = np.random.randint(1, 10, size = 3)
uniform = np.random.uniform(1, 10, size = 3)
choice = np.random.choice([1, 2, 3, 4, 5])

print(seed, "\n")
print(rand, "\n")
print(randn, "\n")
print(randint, "\n")
print(uniform, "\n")
print(choice, "\n")

None 

[0.37454012 0.95071431 0.73199394] 

[-1.11188012  0.31890218  0.27904129] 

[8 3 6] 

[1.50770421 7.49798895 9.44697438] 

2 

