In [2]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

## Metadatas

In [5]:
dimensions = arr.shape
num_of_dim = arr.ndim
count = np.size
data_type = arr.dtype
bytes_per_element = arr.itemsize
total_bytes = arr.nbytes
transposed = arr.T

print("Original Array:")
print(arr)
print()

print(f"Dimensions: {dimensions}")
print(f"Number of dimensions: {num_of_dim}")
print(f"Count: {count}")
print(f"Data type: {data_type}")
print(f"Bytes per element: {bytes_per_element}")
print(f"Total bytes: {total_bytes}")
print(f"Transposed: \n{transposed}")

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimensions: (3, 3)
Number of dimensions: 2
Count: <function size at 0x7f1c05f1efb0>
Data type: int64
Bytes per element: 8
Total bytes: 72
Transposed: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
