In [2]:
import numpy as np

In [3]:
grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(grid[1, 2]) # Single element
print(grid[:, 1]) # Column
print(grid[1, :]) # Row
print(grid[0, : : -1]) # Reverse row

6
[2 5]
[4 5 6]
[3 2 1]


In [4]:
arr = np.random.randint(1, 50, size = (6, 4))
arr

array([[29, 44, 15, 19],
       [32, 41,  7, 35],
       [43,  6, 22,  3],
       [49, 31,  9, 45],
       [14,  2, 49,  1],
       [ 8,  6, 44, 36]])

In [5]:
arr[0]      # First row

array([29, 44, 15, 19])

In [6]:
arr[-1]

array([ 8,  6, 44, 36])

In [7]:
arr[0:2]

array([[29, 44, 15, 19],
       [32, 41,  7, 35]])

In [8]:
arr[2, 2]   # 3rd row, 3rd column

np.int64(22)

### In 2D Arrays

In [10]:
arr[2:5, 1:4]       # Row start:Row stop, col start:col stop

array([[ 6, 22,  3],
       [31,  9, 45],
       [ 2, 49,  1]])

### Boolean indexing

In [17]:
arr > 24

array([[ True,  True, False, False],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [16]:
arr[arr > 24]

array([29, 44, 32, 41, 35, 43, 49, 31, 45, 49, 44, 36])