In [1]:
import numpy as np

arr = np.random.randint(0, 10, size = (3, 6))
arr

array([[7, 1, 5, 9, 5, 1],
       [5, 6, 7, 8, 3, 8],
       [8, 1, 9, 5, 7, 4]])

In [2]:
arr = arr.reshape(6, 3)       # The multiple of reshaped array size should be same as that of og array
arr

array([[7, 1, 5],
       [9, 5, 1],
       [5, 6, 7],
       [8, 3, 8],
       [8, 1, 9],
       [5, 7, 4]])

In [7]:
arr.transpose()             # Transpose of matrix

array([[7, 9, 5, 8, 8, 5],
       [1, 5, 6, 3, 1, 7],
       [5, 1, 7, 8, 9, 4]])

In [8]:
arr.flatten()       # Convert matrix in 1D, always returns a copy

array([7, 1, 5, 9, 5, 1, 5, 6, 7, 8, 3, 8, 8, 1, 9, 5, 7, 4])

In [9]:
arr.ravel()         # Convert matrix in 1D, a view when possible, faster

array([7, 1, 5, 9, 5, 1, 5, 6, 7, 8, 3, 8, 8, 1, 9, 5, 7, 4])

In [10]:
arr.swapaxes(0, 1)          # Swap any two axes, useful beyond 2D

array([[7, 9, 5, 8, 8, 5],
       [1, 5, 6, 3, 1, 7],
       [5, 1, 7, 8, 9, 4]])