In [1]:
import numpy as np

arr = np.random.randint(0, 100, size = (3, 3))
arr

array([[37, 70, 25],
       [44, 16, 20],
       [51, 31, 16]])

In [2]:
arr.sum()

np.int64(310)

In [3]:
arr.mean()

np.float64(34.44444444444444)

In [4]:
np.median(arr)

np.float64(31.0)

In [5]:
arr.std()

np.float64(17.082226703091216)

In [6]:
arr.var()

np.float64(291.80246913580254)

In [7]:
arr.min()

np.int64(16)

In [8]:
arr.max()

np.int64(70)

In [9]:
arr.argmin()

np.int64(4)

In [10]:
arr.argmax()

np.int64(1)

In [11]:
np.percentile(arr, 90)

np.float64(54.800000000000004)

In [12]:
np.quantile(arr, 0.9)

np.float64(54.800000000000004)

In [13]:
np.unique(arr)

array([16, 20, 25, 31, 37, 44, 51, 70])

In [14]:
np.count_nonzero(arr)

np.int64(9)

In [15]:
arr = np.random.randint(0, 100, size = (5, 5))
arr

array([[12, 84, 36, 29, 26],
       [72, 48, 61, 75, 24],
       [27, 40, 17, 36, 73],
       [35, 97, 32,  3, 76],
       [37, 81, 91, 54, 49]])

In [18]:
arr.mean(axis = 0)      # Axis 0 = columns

array([36.6, 70. , 47.4, 39.4, 49.6])

In [19]:
arr.mean(axis = 1)      # Axis 1 = rows

array([37.4, 56. , 38.6, 48.6, 62.4])